dist: xenial
os: linux

language: java
jdk: openjdk8

install: true

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 25%

script:
  - mvn jacoco:prepare-agent -Prelease-all clean install -U
  - mvn jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
