language: java
sudo: false

jdk:
  - openjdk8

install: true

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent -Prelease-all clean install -U

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
